### ISSUE TITLE
water despawn

### ISSUE THREAD

**Issue by gilnett** [Technici4n/Powah#100]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.18.2
- fabric
- Powah:3.0.8 

#### Issue description:
...

in 1.18.2 on fabric. when leaving an area and returning later the water disappears from the reactor
...

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))

...

**Comment by Technici4n** [comment]
Sorry but I only support 1.19.2+ at the moment. The 1.18.2 version has a number of unfixed bugs.
