### ISSUE TITLE
Energy Cells are missing specs info in Powah manual and JEI

### ISSUE THREAD

**Issue by xylix** [Technici4n/Powah#103]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.20.1
- Forge: 47.1.3
- Powah: 5.0.1

#### Issue description:
The in-game powah manual and JEI cannot see energy cell specs in the way that other Powah items show them. Example:

Nitro energy cell:
![image](https://github.com/Technici4n/Powah/assets/13387304/279ffbef-818d-413a-a055-3d6470547d8d)
Nitro discharger:
![image](https://github.com/Technici4n/Powah/assets/13387304/85401058-bb6c-494d-8629-7af210ecd947)

#### Steps to reproduce:
Open minecraft with Powah installed, check the in-game manual. Or check JEI.

**Comment by Technici4n** [comment]
Fixed in #114.
