### ISSUE TITLE
Mining any uraninite ore with a silk touch pickaxe drops nothing.

### ISSUE THREAD

**Issue by HatzzzJhon** [Technici4n/Powah#105]
Version:

- Minecraft: 1.20.1
- Forge: 47.1.47
- Powah: 5.0.2

#### Issue description:

When i try to mine any type of uraninite ore with a silk touch pickaxe, i get nothing. 

#### Steps to reproduce:

Latest forge version and powah version,  only powah instaled, no other mods.
Enchant a pickaxe with silk touch and mine uraninite.

**Comment by lackooka** [comment]
I have this similar issue

**Comment by Clonephaze** [comment]
To add to this, ANY method of silk touch voids uraninite. I tried with rftools silk quarry cards and ars nouveau silk touch break spell. Both voided the blocks entirely.
