### ISSUE TITLE
Energy Cable not connecting to machines

### ISSUE THREAD

**Issue by lackooka** [Technici4n/Powah#106]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.20.1
- Forge: 47.1.3
- Powah: [v5.0.2]

#### Issue description:

Energy cables are not connecting to the machines, only to "AE2 Energy acceptor block"

#### Steps to reproduce:

Use basic Furnator, Energizing Rod.

#### Is this a crash?, please include it here: (Recommended to use [Gist](https://gist.github.com/))

Not a crash!

[kép_2023-09-18_104120029](https://github.com/Technici4n/Powah/assets/83063334/2b7888e9-9124-473d-962c-b9e335483c0a)

**Comment by 62832** [comment]
Remove OptiFine.

**Comment by lackooka** [comment]
that works! thanks
