### ISSUE TITLE
Feature: Energizing orb recipe for forge:ingots/uranium -> uraninite

### ISSUE THREAD

**Issue by atlgeek007** [Technici4n/Powah#11]
Would be nice for 12 recipes in total to generate an appropriate amount of uranium (example: 1 uranium = 1 uraninite, 2 = 2, etc.  along with blocks of uranium -> blocks of uraninite)

**Comment by goldenapple3** [comment]
The equivalent tag for Fabric would be `c:uranium_ingots`
