### ISSUE TITLE
Tooltip formatting problems.

### ISSUE THREAD

**Issue by geosskk** [Technici4n/Powah#111]
# Version:

- Minecraft: 1.20.1
- Forge: 47.0.1
- Fabric Loader: 0.14.21
- Powah: 5.0.2

# Issue description:
## It seems as though some of the text formatting for item tooltips is not working correctly.
![image](https://github.com/Technici4n/Powah/assets/32211101/7c4074bf-4af4-4839-a9d1-1f6bbe2edb7f)

### Possible Solution:

After taking a look at the source code I noticed that a lot of the localized Components were written as:
`Component.literal(getGeneration()).append(Component.translatable("info.lollipop.fe.pet.tick"))`,
which appends the `%s FE/t` to `40k` which results in `40k%s FE/t`.

The issue was that instead of replacing `%s` in the localized string with a value, it appended the localized string to the end value.
It seems to work as expected by using `Component.translatable()` with the key and a replacement value:
`Component.translatable("info.lollipop.fe.pet.tick", getGeneration())`.

![image](https://github.com/Technici4n/Powah/assets/32211101/46d6c781-d6ca-4d16-9109-b6ef6fde6c41)
_Thermo Generator with proper string interpolation._

## There appears to be unnecessary spacing in the tooltips .
![image](https://github.com/Technici4n/Powah/assets/32211101/46d6c781-d6ca-4d16-9109-b6ef6fde6c41)

### Possible Solution:
I'm not sure if this spacing is intentional or not but it seems to be easily removable.
All that has to be done is to remove `tooltip.add(Component.empty());` from the ends of the `appendHoverText()` methods in `AbstractEnergyBlock.java` and `BindingCardItem.java`.

![image](https://github.com/Technici4n/Powah/assets/32211101/8a9c0ba9-8f0e-4f27-ad82-d391a0d09d80)
_Thermo Generator without the spacing at the end of the tooltip._

## There are no tooltips for the Energy Cells.
![image](https://github.com/Technici4n/Powah/assets/32211101/078e736a-4446-4eeb-b234-fa77ab609fb4)

### Possible Solution:
It seems that the class `EnergyCellBlock` returns `EnergyCellItem` in the method `getBlockItem()`.
The `EnergyCellItem` class then overrides the `getEnergyInfo()` method and returns `null`.

The issue with returning `null` from `getEnergyInfo()` is that `appendHoverText` only applies tooltips if `Energy.ifPresent` returns a result.
`Energy.ifPresent` only returns a result when the provided `ItemStack` is an instance of `IEnergyContainingItem` and returns a non null value of `IEnergyContainingItem.Info` from `getEnergyInfo()`.

All that is needed to fix this issue is to remove the 
```
@Override
public Info getEnergyInfo() {
    return null;
}
```
method from the `EnergyCellItem` class.

There doesn't seem to be any issues with removing the `getEnergyInfo()` override from the `EnergyCellItem` class, however I am not 100% certain about this.

![image](https://github.com/Technici4n/Powah/assets/32211101/52f276f4-6b2a-4edb-9acb-91f51b17c368)
_The tooltips of the Energy Cell after these changes._

## The wrench tooltip seems to intend on formatting the current mode text in yellow, but it does not apply.
![image](https://github.com/Technici4n/Powah/assets/32211101/e8e17172-3083-4036-99d6-afc45971db4e)
_The wrench tooltip is completely gray instead of gray and yellow._

![image](https://github.com/Technici4n/Powah/assets/32211101/1d95e669-e6b2-4e0c-ab84-ffe2fefd61e5)
_The mod appends the `ChatFormatting.YELLOW` style right before the wrench mode, but it does not appear in game._

### Possible Solution:
I was thinking that it would be better to separate the "Mode:" and wrench mode localization text.

_Example:_
![image](https://github.com/Technici4n/Powah/assets/32211101/e7ac144c-a2fd-4940-8fe5-3a1d8ad51f72)
I've managed to create a new `"info.powah.wrench.mode"` localization where the current wrench mode can be interpolated into the string.
With this method we can then use a separate `Component.translatable()` for the wrench mode with the `.withStyle(ChatFormatting.YELLOW)` style method.

![image](https://github.com/Technici4n/Powah/assets/32211101/dc405e5f-7d0d-435e-af3f-2f32fbc6e9b2)
_What the wrench tooltip looks like with these changes._

## Notes
I have managed to implement all these changes successfully on the `1.20` branch of this repo.
The changes I've made seem to fix the problems on both the Fabric and Forge versions of the mod.
If it sounds okay, I can submit a PR with all the changes that I've made.

**Comment by Technici4n** [comment]
Sorry, I wasn't looking at issues too closely and missed this part:
> If it sounds okay, I can submit a PR with all the changes that I've made.

Thankfully you went ahead with the PR. :)
