### ISSUE TITLE
Uraninite ore 

### ISSUE THREAD

**Issue by iCloudly** [Technici4n/Powah#117]
1.20.1 Version: (make sure you are on the latest version before reporting):

- Minecraft: ...
- Forge: .47.1.47
- Powah: Powah-5.0.4.jar

#### Issue description:
Uraninite ore cant be mined with Silk Touch ore. when mined with SIlk touch pickaxe urnaninite does not drop loot. It dissapears
#### Steps to reproduce:

...

#### Is this a crash?, please include it here: (Recommended to use [Gist](https://gist.github.com/))

...

**Comment by Technici4n** [comment]
This was fixed in Powah 5.0.3. The server has to update its verison of Powah of course.

**Comment by LuciusV** [comment]
> This was fixed in Powah 5.0.3. The server has to update its verison of Powah of course.

Could you please also fix 1.19.2 version?
