### ISSUE TITLE
Some parts of the config reset with every launch

### ISSUE THREAD

**Issue by Gitcrafter** [Technici4n/Powah#12]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.18.2
- Forge: 1.18.2 40.1.51
- Powah: 3.0.1 beta

#### Issue description:
The configs for "magmatic_fluids", "cooland_fluids", "heat_blocks" and for the energyvalues for blocks and items get reset every time you launch the game, but the configs for worldgen and "energy_per_fuel_tick" aren´t affected by this

#### Steps to reproduce:
1. Change any of the configs for "magmatic_fluids", "cooland_fluids", "heat_blocks" and for the energyvalues for blocks and items while the game is not running and close the configfile afterwards
2. Launch the game and wait until it has finished launching
3. Check the mentioned configs, they now should have reset to their default values, which isn´t what they are supposed to do

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))

there is no crash

**Comment by dog38145** [comment]
Just wanted to butt in and say this also happens for energy values, so it may be the whole config that resets?

**Comment by Gitcrafter** [comment]
no, the configs for the "energy_per_fuel_tick" and the ore rarity don´t reset, I didn´t did more testing, so I don´t know if there are other parts of the config, that are unaffected by the bug
