### ISSUE TITLE
Battery Charging items in inventory causing crash

### ISSUE THREAD

**Issue by hideki2k02** [Technici4n/Powah#127]
Hello, after upgrading Powah! from 4.0.6 to 4.0.11 my game crashes every time upon load. After some digging (and testing) the culprit was the Battery, apparently it is trying to charge something but its crashing.

Latest Logs: https://mclo.gs/py3rv0m
Crash Log: https://mclo.gs/p7Gj9dB

#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.19.2
- Fabric: 0.14.22
- Powah: 4.0.11

**Comment by hideki2k02** [comment]
I guess it COULD BE the code used for charging Trinket slots? Added back in 4.0.7 as seen on this pull request https://github.com/Technici4n/Powah/pull/79

**Comment by shartte** [comment]
I believe (from your crashlog) that this is related to FTBQuest, not Powah.
