### ISSUE TITLE
Impossible to run two separate lines of the same type cable in parallel.

### ISSUE THREAD

**Issue by drewkeating** [Technici4n/Powah#128]
#### Version: 4.0.11

- Minecraft: 1.19.2
- Forge: 43.2.14
- Powah: 4.0.11

#### Issue description: 

Wrench or barehand in any mode (Link, Rotate, Config) won't disconnected connected cables that are next to each other.

#### Steps to reproduce: 

1) Run 2 separate lines of the same cable type (eg. Nitro) in parallel. ![Screenshot](https://github.com/Technici4n/Powah/assets/1873415/2c083ca8-ee74-4065-be37-0e5cc67bf48f)

2) Use the wrench or barehand to disconnect the connected cables so you 
have 2 separate lines running next to each other. (Note, that the screenshot is using different cables to get the desired result.)
![Screenshot](https://github.com/Technici4n/Powah/assets/1873415/7f01564a-c414-447b-a9f5-5ee0e93a48e5)

#### Is this a crash?, please include it here: (Recommended to use [Gist](https://gist.github.com/))

...

**Comment by shartte** [comment]
Powah cables do not support this.
