### ISSUE TITLE
Ender Gate works well in multiplayer?

### ISSUE THREAD

**Issue by seriousfreezing** [Technici4n/Powah#129]
I'd like to know how the energy networking system works in multiplayer mode.
Is each net only marked for one player? Or something like that?

**Comment by Random832** [comment]
Each network is associated with a player ID [rather, each player ID has its own set of numbered channels]. When you break it it remains associated with the player who originally placed it, so moving things around won't cause problems, and e.g. you can have one player in charge of crafting them in bulk and "initializing" them by placing and breaking them if you want to make sure you have one shared network.

**Comment by seriousfreezing** [comment]
Hmmm, just to summarize what I understood: The networks in the Ender Gate are all different for each player id, and if I want to share my network, I have to leave one player responsible for placing and destroying the networks, correct?
