### ISSUE TITLE
Magmators not accepting fluid from pipes

### ISSUE THREAD

**Issue by atlgeek007** [Technici4n/Powah#14]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.18.2
- Forge: 40.1.31
- Powah: 1.18.2 beta

#### Issue description:
magmators won't accept fluid from pipes, just bucketing.

#### Steps to reproduce:
Place magmator, attach via pipe to any tank containing lava, set pipe to extract from tank - the magmator won't take the fluid, you can see in mek pipes that the fluid is there.  I have tried all six faces.

**Comment by Technici4n** [comment]
Works fine with AE2 export busses, so I'll blame it on Mekanism.
