### ISSUE TITLE
Unstable sorting (lack of sorting) in general.heat_blocks section of powah.json5

### ISSUE THREAD

**Issue by yurikus** [Technici4n/Powah#147]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.20.1
- Forge: 47.2.30
- Powah: 5.0.2

#### Issue description:
On every run `powah.json5` is being overwritten, ordering of lines in `general.heat_blocks` keeps changing:

```		"heat_blocks": {
			"powah:blazing_crystal_block": 2800,
			"minecraft:magma_block": 800,
			"minecraft:lava": 1000
		},
```
...
```
		"heat_blocks": {
			"minecraft:lava": 1000,
			"powah:blazing_crystal_block": 2800,
			"minecraft:magma_block": 800
		},
```

etc ...

**Comment by Technici4n** [comment]
These values are now in data maps in 1.21.
