### ISSUE TITLE
[ATM9] Powah config changes on server do not appear in game

### ISSUE THREAD

**Issue by westriel** [Technici4n/Powah#148]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.20.1
- Forge: 47.2.20
- Powah: 5.0.5

#### Issue description:

I am unable to make changes to the powah config actually take affect in game. I have a dedicated server running on my machine for a couple friends. We wanted to change a few things (namely adding new thermo heat blocks for the thermo generators, and changing thermo generator's power generation). I make the changes in the `[server]/config/powah.json5` while the server is offline, start the server and don't see the changes to either thermo heat blocks or their generation rates.

Am I editing the wrong thing? Am I missing a step somewhere?

#### Steps to reproduce:

Make changes to powah config file (config/powah.json5), launch server, join server, no changes reflected.

#### Is this a crash?, please include it here: (Recommended to use [Gist](https://gist.github.com/))

N/A

**Comment by Technici4n** [comment]
Hey, the config is not synced from the server back to the client so the client-side display will be wrong, but the server should have the updated values? So in theory the workflow would be: - update config on the server and all the clients that want to connect to the server. :)

PS: In some future version (probably for Minecraft 1.21 once it is released) I will look into syncing the configuration properly between server and client, unfortunately it doesn't yet!

**Comment by westriel** [comment]
Ah well that makes sense why the math wasn't mathing with what my friend was seeing. Thanks for the update!
