### ISSUE TITLE
Cables won't connect

### ISSUE THREAD

**Issue by Marquinho8790** [Technici4n/Powah#153]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: ...1.20.1
- Forge: ...47.2.21
- Powah: ...5.0.5

#### Issue description:
Cables won't connec
![2024-06-24_17 22 41](https://github.com/Technici4n/Powah/assets/173731750/7f6d71c4-af1f-4de2-addb-50ff7938c897)
t
...

#### Steps to reproduce:

...

#### Is this a crash?, please include it here: (Recommended to use [Gist](https://gist.github.com/))

...

**Comment by Technici4n** [comment]
Remove optifine.
