### ISSUE TITLE
Generators tooltip formatting - contains %s

### ISSUE THREAD

**Issue by louisheimza** [Technici4n/Powah#157]
Version: (make sure you are on the latest version before reporting):

    Minecraft: 1.20.1
    Forge: 47.3.0
    Powah: 5.0.5

Issue description:
In the GUI for any generator, when I hover over the energy bar, the tooltip display is not quite right, as can be seen in the image.
Steps to reproduce:

Hover mouse over energy bar to display tooltip.
Is this a crash?,
It does not seem to affect the game in any way, except for it not looking right.
![image](https://github.com/user-attachments/assets/c4ae043a-e31a-4b82-b703-e78dbcfe9b51)

**Comment by Mithi83** [comment]
I'd say there is already a fix for that waiting as a PR: #156

**Comment by Technici4n** [comment]
Fixed in Powah 5.0.6. Thanks @StarskyXIII!

**Comment by louisheimza** [comment]
Brilliant, thanks very much!
