### ISSUE TITLE
Config not applying to single player game

### ISSUE THREAD

**Issue by RamenNoodles** [Technici4n/Powah#158]
- Minecraft: 1.21
- NeoForge: 21.0.86
- Powah: 6.0.2 beta

In the config I modified the capacities, transfer rates, and generation rates and then loading an existing world or creating a new world the changes don't apply.

![Screenshot 2024-07-20 074254](https://github.com/user-attachments/assets/b3539377-b9fc-4a30-b6ae-1272483e03d6)

![Screenshot 2024-07-20 074339](https://github.com/user-attachments/assets/2a6c3a61-6de1-4d58-9edd-a245f7054933)

**Comment by Twisted6** [comment]
Same problem with a dedicated server after editing both the server and client configs.

Minecraft 1.20.1
Fabric 0.15.11
Powah 5.0.5

**Comment by Technici4n** [comment]
I don't understand the issue? Is the config outright broken? Note that you might have to restart the game for the configs to take effect.

**Comment by RamenNoodles** [comment]
I remember restarting the game multiple times and it would never reflect the changes in the config.

I just tried this again with no other mods except for powah and the changes to the config applied. There might of been a conflict in the mods I  was using, unfortunately I don't remember my mod list.

**Comment by Technici4n** [comment]
I'll take it that Powah is not to blame then 😅
