### ISSUE TITLE
Flux pug doesn't work with Powah Reactor

### ISSUE THREAD

**Issue by EnabledEnzo** [Technici4n/Powah#16]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: ... 1.18.2
- Forge: ... 40.1.31
- Powah: ... 3.0.1

#### Issue description:

when trying to directly attach a flux plug(fluxnetworks) to a reactor the plug isn't extracting. Only reason I mention this is because it worked in the original mod.
#### Steps to reproduce:
set up a functioning reactor 
set up a flux network
attach a flux plug to one of the slots.
attach flux point to any storage and what should happen is the plug extracts and point sends it to storage.

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))

...

**Comment by EnabledEnzo** [comment]
https://www.curseforge.com/minecraft/mc-mods/powah-rearchitected/files      this version of powah.

**Comment by atlgeek007** [comment]
Can confirm I have the same issue - the only way flux plugs work is to use mekanism cables.  Powah cables and Energy Pipez didn't work.

**Comment by Technici4n** [comment]
Probably a bug with these cables because I see no reason why it shouldn't work.

![image](https://user-images.githubusercontent.com/13494793/178596327-99b45203-2b36-44c0-b9cd-157b8dcf531a.png)

**Comment by BloCamLimb** [comment]
Put aside this issue first, your https://github.com/Technici4n/Powah/blob/1.18/forge/src/main/java/owmii/powah/forge/ForgeEnvHandler.java#L135 should better return a cached value rather than a new LazyOptional. And you should call
```
event.addListener(() -> { //lazyOptionals.invalidate() })
```
to invalidate these LazyOptional objects.

**Comment by Technici4n** [comment]
I am deliberately ignoring the contract of LazyOptional because I think the design is stupid and the benefits are unclear. I don't think it's related to the issue, since I am just querying the capability and trying to push energy to it. Unless maybe I got the direction wrong?

**Comment by Technici4n** [comment]
Yes, it seems like I forgot to add `.opposite` somewhere... Should be an easy fix.
