### ISSUE TITLE
Centrifuge recipe Missing for uraninite comb

### ISSUE THREAD

**Issue by DropBear28** [Technici4n/Powah#17]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: ...1.18.2
- Forge: ...40.1.31
- Powah: ...3.0.1-beta

#### Issue description:
...Productive Bees, honeycomb has been added but no recipe has been added in the centrifuge  for unaninite production.

Thanks

**Comment by castilio20** [comment]
You know that productice bee does the recipe right?powah does nothing
This report should be in productive discord/github

**Comment by Technici4n** [comment]
Not a powah issue, rather a modpack or productive bees issue.

**Comment by castilio20** [comment]
It a productive bee issue and i did report on theire discord

**Comment by DropBear28** [comment]
sorry about that guys appreciate your help @castilio20 and @Technici4n

**Comment by EnabledEnzo** [comment]
to help with your search or a fix "Failed to parse recipe 'productivebees:centrifuge/powah/honeycomb_uraninite[productivebees:centrifuge]'! Falling back to vanilla: com.google.gson.JsonSyntaxException: Unknown item 'powah:uraninite_raw_poor"  Whatever makes the comb recipes is trying to find uranite poor but it doesnt exist in this version of powah. Modpack devs should be able to fix.
