### ISSUE TITLE
Powah batteries not charging anything

### ISSUE THREAD

**Issue by atlgeek007** [Technici4n/Powah#18]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.18.2
- Forge: 40.1.31
- Powah: 3-beta

#### Issue description:
batteries do not charge anything in player inventory, except powah player transmitters (?)

Player transmitters when attached to a power source charge everything in player inventory including batteries.

Battery has been activated with sneak+rclick, and doesn't function either in inventory, hotbar, or equipped as a curio.

**Comment by MaxFirestorm** [comment]
Seconding on Powah 3.0.1-beta via TNP Limitless 5
