### ISSUE TITLE
Latest version crashes on Fabric server

### ISSUE THREAD

**Issue by petthepetra** [Technici4n/Powah#180]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.20.1
- Fabric: 0.15.11
- Powah: 5.0.6

#### Issue description:

The latest fabric version of Powah crashes on a standalone server, but not on an internal / LAN server.
To my knowledge, this issue only occurs on version 5.0.6, likely due to the chunk-related changes in that version.

> [01:34:54] [main/ERROR]: Failed to start the minecraft server
> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'powah'!
> Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientChunkEvents in environment type SERVER

#### Steps to reproduce:

1. Install version 5.0.6 on a fabric server
2. Attempt to start server
3. Server fails to start
4. Downgrade to version 5.0.5
5. Attempt to start server
6. Server starts

#### Is this a crash?, please include it here: (Recommended to use [Gist](https://gist.github.com/))

https://gist.github.com/petthepetra/3939f5f837e177c77bb002f69d7b9bb6

**Comment by shartte** [comment]
This should be fixed in [5.0.7](https://github.com/Technici4n/Powah/releases/tag/v5.0.7)
