### ISSUE TITLE
JEI support is missing in 1.21.1 Neoforge

### ISSUE THREAD

**Issue by Saereth** [Technici4n/Powah#186]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.21.1
- NeoForge: 21.1.22
- Powah: Powah-6.1.0

#### Issue description:
No recipes are showing in jei for the energizing orb

#### Steps to reproduce:
Fresh instance, only mods are jei, architectury and powah. Check uses on the energizing orb, nothing is shown

#### Is this a crash?, please include it here: (Recommended to use [Gist](https://gist.github.com/))
Not a crash

**Comment by BigMentalProblems** [comment]
same

**Comment by fe-aribeiro** [comment]
same here, I can't see the recipes for items made in the energizing orb

**Comment by Mithi83** [comment]
JEI support was removed in 1.20.2, see https://github.com/Technici4n/Powah/commit/ff5ddc9b0eafbaa0ebc13e3a901543248e77b73d

**Comment by mezz** [comment]
The integration was pretty easy, so I reimplemented it and submitted a PR here:
* https://github.com/Technici4n/Powah/pull/193
