### ISSUE TITLE
Information missing from manual.

### ISSUE THREAD

**Issue by ZoesDev** [Technici4n/Powah#2]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: ... 1.18.2
- Forge: ... 40.1.31
- Powah: ... 3.0.0 pre01

#### Issue description:
... manual doesn't show all of the functions. in 1.16.5 the manual book has the image of the item and the recipe and tips on how to run and is suppose to look like https://cdn.discordapp.com/attachments/983422048292454431/983436402232533112/2022-06-06_11.24.39.png https://cdn.discordapp.com/attachments/983422048292454431/983436402463227984/2022-06-06_11.24.41.png 

But looks like https://cdn.discordapp.com/attachments/983422048292454431/983429619527082045/unknown.png 

#### Steps to reproduce:
... open up the manual and click on a a item. example open the furnator in the manual.

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))
No crash. just no information in the manual
...

**Comment by SkinHeadBaby** [comment]
Also every tab on the manual has a tooltip with the name of the category/item you are hovering on
like this one

![image](https://user-images.githubusercontent.com/12463364/172226648-51b115e8-6036-41ce-a592-04952960afb9.png)
