### ISSUE TITLE
Suggestion: remove the Horizontal Dielectric Rod

### ISSUE THREAD

**Issue by goldenapple3** [Technici4n/Powah#20]
I think since you're removing Poor and Dense Uraninite items, maybe you can remove the equally useless "Dielectric Rod (Horizontal)". You can just have a single Dielectric Rod item with a diagonal texture and maybe both a "horizontal" and "vertical" crafting recipe.

**Comment by fucksophie** [comment]
Yup! Just takes up space.

**Comment by warior456** [comment]
don't forget to add a recipe to convert them

**Comment by Technici4n** [comment]
I'm going to keep this for now because it's a fun (for me) peculiarity of the mod. :P
