### ISSUE TITLE
Missing forge tags

### ISSUE THREAD

**Issue by DMNerd** [Technici4n/Powah#21]
Version: Current

Deepslate uraninite is missing forge:ores/uraninite tag and forge:ores.

Other materials should have tags added, for the benefit of modpack makers/kubejs scripters and addon developers. 
Suggested tags (in kubejs for my personal modpack):

![image](https://user-images.githubusercontent.com/7889445/178738305-22df074e-f1e2-43eb-a93e-c7a03019aebd.png)

**Comment by unix-supremacist** [comment]
same on fabric, however, crystals probably shouldn't have the gem tag, and uraninite is defintely not a gem, those tags should be up to the author to decide or evan not have at all

**Comment by DMNerd** [comment]
Yes, that were just my suggestions
