### ISSUE TITLE
Ender Cell tooltip fixed at 2.1GFE though capacity is higher

### ISSUE THREAD

**Issue by atlgeek007** [Technici4n/Powah#23]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.18.2
- Forge: 40.1.60
- Powah: 3.0.2-beta

#### Issue description:
Ender cell tooltip in The One Probe only says 2.1GFE, though the ender cell actually has a capacity of 40B FE on this channel. 

#### Steps to reproduce:
Craft ender cell and fill it with power cells to get more than 2B FE, then charge it and see tooltip.

Perhaps it would be best if it used 40GFE rather than 40B FE in the UI also.

![2022-07-16_15 31 01](https://user-images.githubusercontent.com/3845395/179369435-641df31d-d9a3-4d29-a427-55726f939bcb.png)

**Comment by Technici4n** [comment]
Forge Energy issue... It doesn't support amounts above 2 billion (MAXINT), so we are forced to round.
