### ISSUE TITLE
Energy Hoppers don't charge items in Create's containers

### ISSUE THREAD

**Issue by AxelTheModder** [Technici4n/Powah#25]
> Apparently, energy hoppers don't do jack to create's depots, belts, ejectors, basins, (smart) chutes, containers on contraptions (portable storage interfaces), or item vaults

 \- me (yes, I posted the exact same [ \_\_ ] on discord ik)

**Architectury Version**: `architectury-4.5.76-forge`
**Powah Version**: `Powah-3.0.2-beta`
**Create Version**: `create-mc1.18.2_v0.5.0c`

**Comment by Technici4n** [comment]
This is a fundamental issue with the way forge manages energy and items, and there is nothing that I can do about it.
