### ISSUE TITLE
[FABRIC] no recipes (usage) for the Energized Orb diisplayed

### ISSUE THREAD

**Issue by MSandro** [Technici4n/Powah#27]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.18.2
- Fabric: 0.14.8
- Powah: 3.0.2

#### Issue description:
I can not see any Recipe for the Orb in REI. I don't know how to craft the Crystals, there is no description in the Manual!

**Comment by Technici4n** [comment]
Duplicate of #4.
