### ISSUE TITLE
[Fabric] Uraninite not smeltable - Datapack Error

### ISSUE THREAD

**Issue by MSandro** [Technici4n/Powah#28]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.18.2
- Fabric: 0.14.8
- Powah: 3.02

#### Issue description:
![image](https://user-images.githubusercontent.com/10937159/182401238-6da779e8-24b6-4c49-9706-13cbe6c2fc2f.png)

Smelting/Blasting Recipe Output has to be a String: 
```
{
  "type": "minecraft:blasting",
  "ingredient": {
	"item": "powah:uraninite_raw"
  },
  "result": "powah:uraninite",
  "experience": 0.7,
  "cookingtime": 100
}
```

**Comment by Technici4n** [comment]
Looks like a KubeJS problem.
