### ISSUE TITLE
Make more recipes recursive

### ISSUE THREAD

**Issue by Technici4n** [Technici4n/Powah#3]
It seems that some things like high tier reactor are a bit too easy to craft. I wouldn't mind making them more expensive, with the understanding that I'd also boost their production rates to compensate for the added crafting effort... ;)

**Comment by atlgeek007** [comment]
I'm definitely okay with the crafts being harder.  if you're generating 100k fe/tick in a single multiblock that's easy to fuel then it should be a relatively complex or expensive craft.

**Comment by 62832** [comment]
Seconded. If it currently works the way I think it works then, in a way, it actually seems fairly awkward to me to have the lower-tier machines still hanging around next to newly-made high-tier as opposed to having those be used in a higher craft as if to be "upgraded" to the next tier.

**Comment by Technici4n** [comment]
I changed the reactor recipe to be recursive, so closing this.
