### ISSUE TITLE
[Enhancement] Addition of a ChargableItemsEvent

### ISSUE THREAD

**Issue by BobVarioa** [Technici4n/Powah#35]
#### Request 
The addition of something like [this](https://github.com/VazkiiMods/Botania/blob/e6d095ff5010074b45408d6cce8ee1e328af3383/Forge/src/main/java/vazkii/botania/api/mana/ManaItemsEvent.java) that allows developers to add items that count as part of a player's inventory.

This could replace [this file](https://github.com/Technici4n/Powah/blob/9bd1fa147ab8f0643ce99c65e411d476364c4d34/forge/src/main/java/owmii/powah/forge/compat/curios/CuriosCompat.java#L21) with simpler code, and additional mod compatibility.

**Comment by Technici4n** [comment]
Interesting, thanks for the suggestion.
