### ISSUE TITLE
Crashed upon something in reactor screen

### ISSUE THREAD

**Issue by Sunekaer** [Technici4n/Powah#44]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.18.2
- Forge: 40.1.80
- Powah: Powah-3.0.5-beta.jar

#### Issue description:
Was using Powah spirited reactor screen, I believe I hovered over the "item charge" icon, but cannot be certain. Crash log contains mouse location upon time of crash

#### Steps to reproduce:
Within a spirited reactor - hover over the charge item slot within the reactor screen.

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))
https://pste.me/@/Mj0sdR5HPI8
...

**Comment by Technici4n** [comment]
Hmmm, interesting. Looks like it's related to emojiful 🤔

**Comment by Technici4n** [comment]
The crash report is gone, but I don't think this is caused by Powah based on my previous comment.
