### ISSUE TITLE
Nitro Magmator only produces 10k FE/t

### ISSUE THREAD

**Issue by stinyc** [Technici4n/Powah#50]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: ... 1.18.2
- Forge: ... 40.1.84
- Powah: ... 3.0.5-beta

#### Issue description:
...
The nitro tier Magmator from Powah says that it produces 40,000 FE/t, however when pumping them full of lava they only generate 10,000 FE/t.

#### Steps to reproduce:
...
Place nitro Magmator
Fill with lava
Pump into flux network and see it only produce 10,000 FE/t

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))

... N/a

Screenshots:
![2022-11-17_20 45 22](https://user-images.githubusercontent.com/20892446/202597751-667262cb-da6f-4085-913b-e478cbb3140c.png)
![2022-11-17_20 45 27](https://user-images.githubusercontent.com/20892446/202597753-6d672229-367c-40ff-a6c5-19da07fb8006.png)

**Comment by Technici4n** [comment]
Are you playing on a server? The server's config might not match your local config.

**Comment by stinyc** [comment]
The screenshots above were taken on a single player test world. Also I made sure to check the configs and they did say that it should generate the correct amount.

**Comment by stinyc** [comment]
Also, it should be a problem with the spirited tier (my bad!)

**Comment by Technici4n** [comment]
Ok, I figured this out: magmators hard-limit themselves to consuming 100 mb of fluid each tick, which for lava means that it produces 10 kFE/t. You can increase this limit by tweaking the config, or adding extra rarer and more powerful fluids:

```json5
		// List of fluids used in the Magmator.
		"magmatic_fluids": {
			"minecraft:lava": 10000
		},
```

I agree that this is misleading, am I am planning to rework and rebalance the system entirely to make it clearer and better. Closing as superseded by #10.
