### ISSUE TITLE
All energizing rods bind to the same orb

### ISSUE THREAD

**Issue by Seegras** [Technici4n/Powah#51]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.18.2
- Forge: 40.1.84
- Powah: 3.0.5-beta

#### Issue description:
When in reach, all energizing rods will bind to the same orb. If that orb does not contain any materials, but other orbs right next to them do, nothing will happen and it does appear as if they're broken. 

The only way to get to recognize them another orb is to break the old one. 

Also, they won't bind to the nearest orb, but to another orb further away if another energizing rod already uses this. This makes production of multiple materials at the same time extremely tedious or, if they're not far away enough, impossible. 

#### Steps to reproduce:

Just place two orbs a meter apart, both containing recipes, and place some energizing rods near them and see what happens.

**Comment by Technici4n** [comment]
You can choose the target orb using a Powah wrench.

**Comment by Seegras** [comment]
oops. My derp. Sorry for bothering you.
