### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by Shybella** [Technici4n/Powah#52]
delete

**Comment by Shybella** [comment]
Cables also caused excessive packet size inside of Compact Machines, such as cable coordinate location

**Comment by Shybella** [comment]
Packet error: https://pastebin.com/raw/HvM3vrMN

**Comment by Technici4n** [comment]
The first crash is actually an AE2 bug. For the packet spam, I have no idea what exactly is causing it; I will eventually look at it, but it might take a while.

**Comment by Shybella** [comment]
> The first crash is actually an AE2 bug. For the packet spam, I have no idea what exactly is causing it; I will eventually look at it, but it might take a while.

Let me know if I can get you anymore data, logs, etc. I'll attempt to get you whatever you need and if I find anything pointing toward the cause I will post here. Thanks

**Comment by Technici4n** [comment]
Thanks for the offer. I will probably be able to figure things out. Just know that the next round of Powah bug fixes is probably not happening before a few weeks. 😅
