### ISSUE TITLE
1.18.2 fabric crash when cable attaches to TR IDSU

### ISSUE THREAD

**Issue by Linguardium** [Technici4n/Powah#57]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.18.2
- Fabric 

#### Issue description:
Powah attempts to query the Energy API for sided power support in order to determine connection support. This query is not supported by the 1.18.2 energy api. A fix was developed for 1.19.2 updating the TR energy api for FAPI transfer/storage api parity but this change is not included in 1.18.2 so the 1.18.2 Powah release should not be attempting to query the energy api from clientside

https://github.com/TechReborn/TechReborn/issues/3002

**Comment by Technici4n** [comment]
The energy API still supports all the versions above 1.17 afaik, so the fix must be applied to TR.

**Comment by Linguardium** [comment]
Well, that appears to be an argument between you and other devs of TR i guess. They have already said they do not support 1.18.2 and that powah needs to be where the fix is applied. 
![image](https://user-images.githubusercontent.com/61733861/206326150-09a6ca02-2634-469d-90d7-91e6577a7298.png)

**Comment by Technici4n** [comment]
Fixed in TR 5.2.1 (now building).
