### ISSUE TITLE
[Feature Request] Charge items in trinkets slots

### ISSUE THREAD

**Issue by Nemo157** [Technici4n/Powah#65]
[Applied Energistics 2 Wireless Terminals](https://modrinth.com/mod/applied-energistics-2-wireless-terminals) adds terminals that can be placed in [Trinkets](https://www.curseforge.com/minecraft/mc-mods/trinkets) slots and need power. With a bound Player Transmitter these terminals get charged when in the main inventory, but not when placed in the trinket slot. It would be useful if the Trinkets mod was detected and added to the slots to check for charging.

**Comment by Technici4n** [comment]
Implemented in #79.
