### ISSUE TITLE
Crash upon server boot. (Cable added to position BlockPos{}, but there was already one there?)

### ISSUE THREAD

**Issue by Gbergz** [Technici4n/Powah#71]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.19.2
- Forge: 43.2.0
- Powah: 4.0.6

#### Issue description:
Some kind of crash with AE2 and Powah cables.

#### Steps to reproduce:
Not sure exactly how to reproduce as this was on a public server.
Start server
Wait.
Crash.

#### Crash Report
https://gist.githubusercontent.com/Gbergz/d530c4b41962c464adfbdb92d28a56ef/raw/82de0fe92b1a1d267e337987a7883d6983b36eb1/gistfile1.txt

**Comment by byRandom** [comment]
I've got the same problem, but it won't happen on server boot, I would happen after some time of playing on a server.

**Comment by Bilanglosigkeit** [comment]
Same error
Happens in Singleplayer when I enter the Nether

**Comment by Technici4n** [comment]
This is actually an ME Controller bug

**Comment by ChaosBasilisk** [comment]
I am having this same issue. Seems to occur when in "The Other" or the Nether. It does appear to be related to the RS Controller, however. Doesn't seem to matter which face the cable is connected to either

**Comment by ChaosBasilisk** [comment]
https://mclo.gs/7S4sTj0 This is the crash log as well for reference.

**Comment by Sewdohe** [comment]
I had a player on my server laying cables and they started multiplying. Now when he tries to re-join it just spawns MORE cables on top of the cables. 

I deleted his player data, and he can join the server again but now he crashes it.

**Comment by satoon10** [comment]
Still happens to me. Here's [my log](https://gist.githubusercontent.com/satoon10/fece33c127385cad1a0a2df10caf7bec/raw/fa8921c0981ad5bba0c1ecc79d88cbbd9ccd0485/crash-2023-05-09_07.10.24-server.txt).

**Comment by Technici4n** [comment]
@satoon10 This is a bug with integrated dynamics loading a chunk while it's being unloaded, please report it to then.
