### ISSUE TITLE
Changing config crashes game

### ISSUE THREAD

**Issue by IanLuminus** [Technici4n/Powah#78]
- Minecraft: 1.19.2
- Forge: 43.2.6
- Powah: 4.0.6
- AllTheMods 8 most recent as of 3/19

#### Issue description:
Just wanted to tweak the power generation of solar panels.. then soon as I get loaded into the game, it crashes without generating an actual crash log or an error in debug.log or anything. Just game-disappears-like-it-never-loaded crash to desktop.

#### Steps to reproduce:
Load ATM8
Search "Solar"
Close game
Open powah.json5
Edit solar panel generation values, save and close
Load into game world

#### Notes:
I.. don't know if this is specific to just this mod, some JEI plugin, or some other mod conflict (but I doubt that last one because why would a mod conflict arise just from changing values within a config? It's not like they're needed for block number assignments anymore).

**Comment by Technici4n** [comment]
Please post at least a log. I can't help you otherwise.

**Comment by IanLuminus** [comment]
https://gist.github.com/IanLuminus/0af902809fed8c639e5e0128bf467408
https://gist.github.com/IanLuminus/de3505bbd1e1917c1b912f57a0f76cef

Deleting and generating a clean config *does* fix it and gameplay is able to resume, so I hope that knowing that and having these (I didn't think the log would be helpful because it wasn't showing any errors or anything that I could find) will help some.

**Comment by Technici4n** [comment]
Can you post latest.log? Debug log is too verbose

**Comment by IanLuminus** [comment]
That's what the first link is, the last latest.log that had the crash. As I mentioned before, deleting the config and generating a clean one stops the crash, so my current latest.log is from a successful load into the game.

**Comment by Technici4n** [comment]
Ah right, sadly I can't do much since the error is not in these logs. I suspect it's a config syntax error but it's hard to say
