### ISSUE TITLE
Blocks are not harvestable

### ISSUE THREAD

**Issue by goldenapple3** [Technici4n/Powah#8]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.18.2
- Quilt: 0.17.0
- Powah: 3.0.0-alpha

#### Issue description:
Powah blocks take forever to break and do not drop themselves

**Comment by Cy699** [comment]
yeah ive noticed this too, definitely a big issue

**Comment by goldenapple3** [comment]
3.0.1-alpha mostly fixes this as far as I can tell, but deepslate ores are not harestable

**Comment by Technici4n** [comment]
Goddamn, I thought I had fixed this. :/
