### ISSUE TITLE
Cables not connecting with optifine

### ISSUE THREAD

**Issue by iamkitsunekun** [Technici4n/Powah#92]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: ...1.19.2
- Forge: ... 43.2.9
- Powah: ...4.0.10

#### Issue description:
...When optifine (HD U I1) is used the cables don't connect or extract power from anything related to the mod, but will connect with blocks from other mods

#### Steps to reproduce:
...
Having both optifine (HD U I1) and powah, removed every other mod and just left these two and still happened
#### Is this a crash?, please include it here: (Recommended to use [Gist](https://gist.github.com/))
Does not crash
...
![2023-05-14_17 45 01](https://github.com/Technici4n/Powah/assets/133608561/f8d5b46f-a1a7-46dc-8630-cbb32c59bdd1)

**Comment by Sea-Kerman** [comment]
The solution is to not use optifine. Rubidium and Oculus are good alternatives, they’re the forge ports of Sodium and Iris
