### ISSUE TITLE
Wires and pipes not connected

### ISSUE THREAD

**Issue by NeffBr** [Technici4n/Powah#94]
- Minecraft: 1.19.2
- Forge: 43.2.6
- Powah: 4.0.10

hi, there are no wires and pipes connected to my powah mod client, why?

**Comment by Technici4n** [comment]
Do you have OptiFine? If so, remove it.

**Comment by NeffBr** [comment]
Хорошо, оно работает без optife, но как сделать чтобы они были совместимы?

**Comment by NeffBr** [comment]
Okay, it works without optife, but how do I make them compatible? I need optife in my build.

**Comment by Technici4n** [comment]
You can't. Please use Rubidium and Oculus for performance and shaders.

**Comment by NeffBr** [comment]
Ok, then tell me more, how to combine the mod powah with other wires from other mods, such as pipez?
