### ISSUE TITLE
Not working with EMI | 1.20.1 fabric

### ISSUE THREAD

**Issue by Surpos0** [Technici4n/Powah#95]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.20.1
- Fabric
- Powah: 5.0 alpha

#### Issue description:
crashing EMI, like not whole minecraft but EMI can't load recipes when this mod is on
#### Steps to reproduce:
...

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))

...

**Comment by cswimr** [comment]
Also having this issue, here's the EMI crash log:
https://haste.seaswimmer.cc/adufeyudos
This is **not a Minecraft crash**, this is EMI crashing.

After asking in the EMI discord, this is the response I got:
> the class was moved but the entrypoint in fabric.mod.json wasn't updated
