### ISSUE TITLE
Cable connection error + optifine mod

### ISSUE THREAD

**Issue by ChibeMeliodas** [Technici4n/Powah#96]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.20.1
- Forge: minecraft client-1.20.1-20230612.114412
- Powah: powah (5.0.1)

#### Issue description:
When I use the optifine mod together with the powah mod, the cables end up not connecting, when I remove the optifine mod, the cables connect!

![image](https://github.com/Technici4n/Powah/assets/33189940/42bb1880-87c8-4eec-acc7-aae39d41f66a)

#### Steps to reproduce:

1. enter the world with optifine mod installed
2. put the cable on the side of the machine
3. does not connect
4. close minecraft
5. remove optifine
6. enter the world again
7. connect powah cable to any machine

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))

no crash

**Comment by Technici4n** [comment]
Optifine's fault...
